sudo: required

services:
  - docker

language: node_js

os:
  - linux

before_script:
  - docker pull appcelerator/etcd:3.1.9
  - ./start-etcd.sh
  - cd example/app && npm i && cd ../../
  - sleep 15
  - npm i @npm-wharf/shipwright@latest -g

script:
  # coveralls will _not_ stop rejecting this saying the repo doesn't exist
  # no amount of rename/source redirect/sync attempts have fixed this
  # - nyc npm test && nyc report --reporter=text-lcov | coveralls
  - nyc npm test && nyc report --reporter=text-lcov

after_script:
  - ./kill-etcd.sh

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - shipwright build image --repo=npmwharf --name=kickerd --tags=lm,lt,v,miv,ma --cache-from-latest

node_js:
  - "6"
  - "8"
