sudo: required

services:
  - docker

language: node_js

os:
  - linux

before_script:
  - docker pull alpine:3.4
  - ./start-registry.sh

script:
  - nyc npm test && nyc report --reporter=text-lcov | coveralls

after_script:
  - ./kill-registry.sh

node_js:
  - "4"
  - "6"
